### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by pascalberger**
Fixes a typo in the message sent to Twitter

### CODE REVIEW

**Comment by pascalberger** [comment]
My editor also automatically removed trailing whitespace. Please let me know if you prefer to have only a PR with the typo fix.

**Review by nils-a — APPROVED** [review]
LGTM!

**Comment by nils-a** [comment]
@pascalberger  your changes have been merged, thanks for your contribution :+1:

**Comment by nils-a** [comment]
@all-contributors please add @pascalberger  for code

**Pull request merged**
